engines: 
  csslint: 
    enabled: true
  duplication: 
    config: ~
    enabled: true
    languages: 
      - javascript
  eslint: 
    enabled: true
exclude_paths: 
  - docs/**/*
  - doc/**/*
ratings: 
  paths: 
    - "**.js"
    - "**.cs"
