language: node_js
node_js:
- '6'
addons:
  sauce_connect:
    username: cse112lucky13
    access_key: fb844c65-3161-4d0f-a518-121c00d974a4
before_script:
- npm install -g gulp
script: gulp
notifications:
  slack: cse112lucky13:KZO7RAgO53DaVL2ej8rYGIzh
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: vpQS+0QErqSAHZgLE7ydySk8qt4/V8WZjrkLaiCiyON9Mifj8eQ013kapcpBSjxMcW6GEIj2/pn1cG3EdFHnebBdv/hLpQhOrLB0looSTdsqHHKxqoxj2FA36Pqc5alwTka+kspoeSK9Tb7MCcaLyqPLtJoedcoXclmuF9VRzNrun/uRJiHnvgSpfSYmprT6/LGqspGV/gSphOQtPm59HlHnL7sWR8Y9tUcvqyCj2Mzya/xxzt+t5jT6ivU7dPhVBjPegi0EALazOQNB5z1c/VAhskBRHZRtToG8lBL1OHPAgqka+q0CJz80/B5PqJf60GEfLx50BVeWjWKxun4GXCvkxcGMivgCs53/hNwHnaroQl5yst0594l2YqkIJSutj922/ZyzRnCPByan2+s5rpajOn57AqR8dg2spy4bWrNeRLkIBtSdY72IPsqec3fuKvVxRBKEsI1bUZtpIMrtbChjnfMDsvRtpjU+gIQAM6i60p6fCQy1/m71q6jmkC/C3YOSzOxouIwJ2vlfmAsXDONGlM66Ms90gRYThNK2CCtX1smPe0iFdVDnXCVO5xDHLwP1Pd+QAuNpRkp41ijoPA2zIW0ec8Jcr5wSI4tXlqfOA5I+2ureem12zdVP1JrICd5FznNeU/aYiqKzZ0KSxDNWtanvcSC9ZilWMpxNT84=
  app: 
    master: lucky13
    develop: lucky13-dev
  on:
    repo: aframr/cse112GettingStarted
    all_branches: true
